# Generated by Django 6.0.3 on 2026-03-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100)),
                ('attack_type', models.CharField(choices=[('SQL Injection', 'SQL Injection'), ('XSS', 'XSS'), ('Brute Force', 'Brute Force'), ('Command Injection', 'Command Injection'), ('Directory Traversal', 'Directory Traversal'), ('Normal', 'Normal')], default='Normal', max_length=100)),
                ('payload', models.TextField()),
                ('target', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Blocked', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Attacker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(default='Unknown', max_length=100)),
                ('total_attacks', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_alerts', models.BooleanField(default=True)),
                ('blocked_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_password', models.CharField(default='admin123', max_length=200)),
            ],
        ),
    ]
